services:
  mercurjs:
    build:
      context: .
      args:
        MERCURJS_VERSION: ${MERCURJS_VERSION}
        NODE_MAJOR: ${NODE_MAJOR}
    image: mercurjs
    container_name: mercurjs-dev
    network_mode: host
    env_file:
      - .env
    environment:
      MERCURJS_VERSION: ${MERCURJS_VERSION}
      NODE_MAJOR: ${NODE_MAJOR}
    volumes:
      - bun-cache:/root/.bun/install/cache
      - npm-cache:/root/.npm

  postgres:
    image: postgres:16
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  bun-cache:
  npm-cache:
  pgdata: