services:
  mercurjs:
    build:
      context: .
    image: mercurjs
    container_name: mercurjs-dev
    network_mode: host
    volumes:
      - bun-cache:/root/.bun/install/cache
      - npm-cache:/root/.npm

  postgres:
    image: postgres:16
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MERCURJS_VERSION: ${MERCURJS_VERSION}
      NODE_MAJOR: ${NODE_MAJOR}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  bun-cache:
  npm-cache:
  pgdata: